name: Merge from Pipeline to Main

on:
  push:
    branches:
      - pipeline 
jobs:
  sync_pipeline_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Setup authentication
        run: |
          git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git          

      - name: Checkout main branch
        run: |
          git checkout main
          git pull origin main
      - name: Merge pipeline into main
        run: |
          git merge --no-ff pipeline -m "Auto-merged pipeline into main"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}